name: SquidASM backend tests

on: [push, pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 30  # if squidasm is not compatible, it might get stuck. Waiting any longer won't help!
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install netqasm
      run: make install-dev
    - name: Install squidasm
      run: pip install -e .[squidasm] --extra-index-url https://${{ secrets.NETSQUIDPYPI_USER }}:${{ secrets.NETSQUIDPYPI_PWD }}@pypi.netsquid.org
      continue-on-error: true  # Allow failure because squidasm's develop branch may not be up-to-date with the changes in NetQASM we're checking right now
    - name: Run tests
      run: make external-tests
      continue-on-error: true  # Allow failure because squidasm's develop branch may not be up-to-date with the changes in NetQASM we're checking right now
  examples:
    name: Run examples
    runs-on: ubuntu-latest
    timeout-minutes: 30  # if squidasm is not compatible, it might get stuck. Waiting any longer won't help!
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install netqasm
      run: make install-dev
    - name: Install squidasm
      run: pip install -e .[squidasm] --extra-index-url https://${{ secrets.NETSQUIDPYPI_USER }}:${{ secrets.NETSQUIDPYPI_PWD }}@pypi.netsquid.org
      continue-on-error: true  # Allow failure because squidasm's develop branch may not be up-to-date with the changes in NetQASM we're checking right now
    - name: Run examples
      run: make external-examples
      continue-on-error: true  # Allow failure because squidasm's develop branch may not be up-to-date with the changes in NetQASM we're checking right now
